src/pxsrt/images/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired


class UploadForm(FlaskForm):
    file = FileField('File',
                     validators=[DataRequired(), FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Upload')

src/pxsrt/images/routes.py
from flask import render_template
from flask import url_for
from flask import flash
from flask import redirect
from flask import request
from flask import abort
from flask import Blueprint
from flask import jsonify
from flask_login import current_user, login_required
from pxsrt import db
from pxsrt.models import Upload
from pxsrt.images.utils import save_image, instantiate_pxsrt_obj
from pxsrt.images.forms import UploadForm


images = Blueprint('images', __name__)


@images.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm()
    if form.validate_on_submit():
        if form.file.data:
            upload_filename = save_image(form.file.data, 'uploads')
            upload = Upload(filename=upload_filename, author=current_user)
            db.session.add(upload)
            db.session.commit()
            flash('File uploaded', 'success')
            return redirect(url_for('main.home'))
    return render_template('upload.html', title='File', form=form)


@images.route('/image/<int:upload_id>', methods=['GET', 'POST'])
@login_required
def image(upload_id):
    image = Upload.query.get_or_404(upload_id)

    return render_template('image.html', image=image)


@images.route('/image/preview', methods=['POST'])
@login_required
def view_thresh():
    upload_id = request.form['image_id']
    image = Upload.query.get_or_404(upload_id)
    pxsrt_obj = instantiate_pxsrt_obj(image.filename)
    pxsrt_obj.load_image_data()
    pxsrt_obj.set_user_choices(
                                request.form['mode'],
                                request.form['threshold'],
                                request.form['direction'],
                                request.form['upper'],
                                request.form['reverse']
    )
    pxsrt_obj.read_thresh()
    t_filename = pxsrt_obj.generate_thresh()
    image.t_filename = t_filename
    db.session.commit()

    return jsonify({
            'result': 'success',
            'path': 'img/thresh/',
            'filename': t_filename
            })


@images.route('/image/sort', methods=['POST'])
@login_required
def view_sort():
    upload_id = request.form['image_id']
    image = Upload.query.get_or_404(upload_id)
    pxsrt_obj = instantiate_pxsrt_obj(image.filename)
    pxsrt_obj.load_image_data()
    pxsrt_obj.set_user_choices(
                                request.form['mode'],
                                request.form['threshold'],
                                request.form['direction'],
                                request.form['upper'],
                                request.form['reverse']
    )
    pxsrt_obj.read_thresh()
    s_filename = pxsrt_obj.sort_pixels()
    image.s_filename = s_filename
    db.session.commit()

    return jsonify({
            'result': 'success',
            'path': 'img/sorts/',
            'filename': s_filename
            })


@images.route('/image/refresh', methods=['POST'])
@login_required
def refresh():
    upload_id = request.form['image_id']
    image = Upload.query.get_or_404(upload_id)

    return jsonify({
            'result': 'success',
            'path': 'img/uploads/',
            'filename': image.filename
            })


@images.route('/image/<int:image_id>/delete', methods=['POST'])
@login_required
def delete_image(image_id):
    image = Upload.query.get_or_404(image_id)
    if image.author != current_user:
        abort(403)
    db.session.delete(image)
    db.session.commit()
    flash('Image Deleted', 'success')
    return redirect(url_for('main.home'))

src/pxsrt/main/routes.py
from flask import render_template, Blueprint
from flask_login import current_user
from pxsrt.models import Upload


main = Blueprint('main', __name__)


@main.route('/')
def home():
    uploads = Upload.query.all()
    bgcolor = "white" if current_user.is_authenticated else "transparent"
    return render_template('home.html', uploads=uploads, bgcolor=bgcolor)

src/pxsrt/users/routes.py
from flask import render_template, url_for, redirect, request, flash, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from pxsrt import db, bcrypt
from pxsrt.models import User
from pxsrt.users.forms import RegisterForm, LoginForm, UpdateAccountForm
from pxsrt.images.utils import save_image


users = Blueprint('users', __name__)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(
                    url_for('main.home'))

        else:
            flash('Login Failed', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
                                                        form.password.data
                                                        ).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created. Welcome, {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.profpic.data:
            profpic_filename = save_image(form.profpic.data, 'profpics')
            current_user.profpic = profpic_filename
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account successfully updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profpic = url_for('static',
                      filename='img/profpics/' + current_user.profpic)
    return render_template('account.html',
                           title='Account', form=form, profpic=profpic)

src/pxsrt/templates/account.html
{% extends "main.html" %}
{% include "leftSideNav.html" %}
{% include "topNav.html" %}
{% block content %}
  <div class="content">
    <div class="row" id="user-info-row">
      <img class="rounded-circle account-img" src="{{ profpic }}" alt="">
      <div class="user-info">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="account-p">{{ current_user.email }}</p>
      </div>
    </div>
    <form class="user-update-info-form" action="" method="post" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="mb-5">Update Info</legend>
        <div class="form-group">
          {{ form.username.label(class="form-control-label") }}
          {% if form.username.errors %}
            {{ form.username(class="form-control form-control-md is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.username(class="form-control form-control-md") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-md is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control form-control-md") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.profpic.label() }}
          {{ form.profpic(class="form-control-file") }}
          {% if form.profpic.errors %}
            {% for error in form.profpic.errors %}
              <span class="danger">{{ error }}</span><br>
            {% endfor %}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group" id="updateAccountButton">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>
  </div>
{% endblock content %}

src/pxsrt/templates/home.html
{% extends "main.html" %}
{% include "leftSideNav.html" %}
{% include "topNav.html" %}
{% block content %}
{% if current_user.is_authenticated %}
  <div class="row">
      {% for upload in uploads %}
        <div class="img-container col-md-4">
          <a href="{{ url_for('images.image', upload_id=upload.id) }}">
            <img class="img-fluid" src="{{ url_for('static', filename='img/uploads/' + upload.filename) }}" alt="">
          </a>
        </div>
      {% endfor %}
  </div>
{% else %}
  <div class="landing-logo-container">
    <a href="/login">
      <svg xmlns="http://www.w3.org/2000/svg" width="400" height="200" viewBox="0 0 400 200">
        <text id="PxSrt" transform="translate(0 150)" font-size="150" font-style="oblique"><tspan x="0" y="0">PxSrt</tspan></text>
      </svg>
    </a>
  </div>
  <div class="landing-img-container"></div>
{% endif %}
{% endblock content %}

src/pxsrt/templates/image.html
{% extends "main.html" %}
{% include "leftSideNav.html" %}
{% include "topNav.html" %}
{% block content %}
  <div class="imgpg-header">
    <h4>{{image.filename}}</h4>
  </div>
  <img id="imgpg-img" src="{{ url_for('static', filename='img/uploads/' + image.filename) }}" alt="">
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Image?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('images.delete_image', image_id=image.id) }}" method="post">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
{% block toolbar %}
  <div class="sidebar" id="toolbar">
    <form method="post" enctype="multipart/form-data">
      <div class="form-group row" id="modeFormGroup">
        <label class="col-sm-4" for="mode">Mode</label>
        <select class="col-sm-8 input-large form-control" name="mode" id="mode" required>
          <option value="H">Hue</option>
          <option value="S">Saturation</option>
          <option value="V">Value</option>
          <option value="R">Red</option>
          <option value="G">Green</option>
          <option value="B">Blue</option>
        </select>
      </div>
      <div class="form-group row" id="thresholdFormGroup">
        <label class="col-sm-4" for="threshold">Threshold</label>
        <input class="col-sm-8" type="range" name="threshold" id="threshold" min="0" max="255" value>
      </div>
      <div class="form-group row" id="directionFormGroup">
        <label class="col-sm-4" for="direction">Direction</label>
        <div class="form-group col-sm-8 directionRadioGroup">
          <div class="row">
            <input id="direction-0" type="radio" name="direction" value="h"></input>
            <label for="direction-0">Horizontal</label>
          </div>
          <div class="row">
            <input id="direction-1" type="radio" name="direction" value="v"></input>
            <label for="direction-1">Vertical</label>
          </div>
        </div>
      </div>
      <div class="form-group row" id="upperFormGroup">
        <label class="col-sm-4" for="upper">Upper</label>
        <div class="checkboxContainer col-sm-8">
          <input class="" type="checkbox" id="upper" name="upper" value="False">
        </div>
      </div>
      <div class="form-group row" id="reverseFormGroup">
        <label class="col-sm-4" for="reverse">Reverse</label>
        <div class="checkboxContainer col-sm-8">
          <input class="" type="checkbox" id="reverse" name="reverse" value="False">
        </div>
      </div>
      <div class="form-group row" id="submitButtonGroup">
        <div class="submitButtonContainer col-sm-4">
          <input class="btn btn-primary toolButton" image_id="{{ image.id }}" id="previewButton" name="preview" value="preview">
        </div>
        <div class="submitButtonContainer col-sm-4">
          <input class="btn btn-primary toolButton" image_id="{{ image.id }}" id="sortButton" name="sort" value="sort">
        </div>
        <div class="submitButtonContainer col-sm-4">
          <input class="btn btn-primary toolButton" image_id="{{ image.id }}" id="refreshButton"  name="refresh" value="refresh">
        </div>
      </div>
    </form>
    <div class="update-options">
      <button type="button" class="btn btn-danger btn-md" data-toggle="modal" data-target="#deleteModal">Delete</button>
    </div>
  </div>
{% endblock toolbar %}

src/pxsrt/templates/leftSideNav.html
{% block leftSideNav %}
{% if current_user.is_authenticated %}
  <nav class="sidebar" id="left-sidenav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="{{ url_for('users.account') }}" class="nav-link">
          <div class="nav-profpic-container">
            <img src="{{ url_for('static', filename='img/profpics/' + current_user.profpic) }}" alt="">
          </div>
          <span class="link-text">{{ current_user.username }}</span>
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ url_for('images.upload') }}" class="nav-link">
          <img src="{{ url_for('static', filename='icons/plus-24.svg') }}" alt="New" class="nav-link-icon">
          <span class="link-text">New</span>
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ url_for('main.home') }}" class="nav-link">
          <img src="{{ url_for('static', filename='icons/file-directory-fill-24.svg') }}" alt="Uploads" class="nav-link-icon">
          <span class="link-text">Uploads</span>
        </a>
      </li>
    </ul>
  </nav>
{% endif %}
{% endblock leftSideNav %}

src/pxsrt/templates/load.html
{% extends "main.html" %}
{% include "leftSideNav.html" %}
{% block content %}
<form class="content-section" method="post" enctype="multipart/form-data">
  {{ load_form.errors }}
  {{ load_form.hidden_tag() }}
  <div class="form-group row" id="loadImageFormGroup">
    <label class="col-sm-4">Load File:</label>
    <div class="col-sm-8">
      {{ load_form.image }}
    </div>
  </div>
  <div class="form-group row">
    {{ load_form.load(class="btn btn-primary toolButton") }}
  </div>
</form>
{% endblock content %}

src/pxsrt/templates/login.html
{% extends "main.html" %}
{% include "leftSideNav.html" %}
{% include "topNav.html" %}
{% block content %}
  <div class="content">
    <form class="" action="" method="post">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend mb-5>Login</legend>
        <div class="form-group">
          {{ form.username.label(class="form-control-label") }}
          {{ form.username(class="form-control form-control-md") }}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          {{ form.password(class="form-control form-control-md") }}
        </div>
        <div class="form-check">
          {{ form.remember(class="form-check-input") }}
          {{ form.remember.label(class="form-check-label") }}
        </div>
      </fieldset>
      <div class="form-group" id="loginButton">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>
    <div class="border-top pt-2">
      <small class="text-muted">
        Don't Have an Account? <a href="{{url_for('users.register')}}">Create Account</a>
      </small>
    </div>
  </div>
{% endblock content %}

src/pxsrt/templates/main.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>PxSrt</title>
  </head>
  <body>
    {% block topNav %}{% endblock topNav %}
    <main>
      <div class="main-wrapper">
        <div class="main-container" style='background-color: {{bgcolor}}'>
          {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
              {% for category, message in messages %}
              <div class="alert alert-{{category}}">
                {{message}}
              </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock content %}
        </div>
      </div>
      {% if current_user.is_authenticated %}
        {% block toolbar %}{% endblock toolbar %}
      {% endif %}
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
  </body>
</html>

src/pxsrt/templates/register.html
{% extends "main.html" %}
{% include "leftSideNav.html" %}
{% include "topNav.html" %}
{% block content %}
  <div class="content">
    <form class="" action="" method="post">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend mb-5>Register</legend>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-md is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control form-control-md") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.username.label(class="form-control-label") }}
          {% if form.username.errors %}
            {{ form.username(class="form-control form-control-md is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.username(class="form-control form-control-md") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-md is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password(class="form-control form-control-md") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.password_confirm.label(class="form-control-label") }}
          {% if form.password_confirm.errors %}
            {{ form.password_confirm(class="form-control form-control-md is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password_confirm.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password_confirm(class="form-control form-control-md") }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group" id="registerButton">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>
    <div class="border-top pt-2">
      <small class="text-muted">
        Already Have an Account? <a href="{{url_for('users.login')}}">Sign In</a>
      </small>
    </div>
  </div>
{% endblock content %}

src/pxsrt/templates/topNav.html
<nav class="navbar navbar-expand-sm" id="topNav">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/">
        <svg xmlns="http://www.w3.org/2000/svg" width="373" height="158" viewBox="0 0 373 158">
          <text id="PxSrt" transform="translate(5 120)" fill="#fff"><tspan x="0" y="0">PxSrt</tspan></text>
        </svg>
      </a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
        <li class="">
          <a class="" href="{{ url_for('users.account') }}">Account</a>
        </li>
        <li class="">
          <a class="" href="{{ url_for('users.logout') }}">Logout</a>
        </li>
      {% else %}
        <li class="">
          <a class="" href="{{ url_for('users.login') }}">Login</a>
        </li>
        <li class="">
          <a class="" href="{{ url_for('users.register') }}">Register</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

src/pxsrt/templates/upload.html
{% extends "main.html" %}
{% include "leftSideNav.html" %}
{% include "topNav.html" %}
{% block content %}
  <div class="content">
    <div class="row" id="upload-img-row">
      <form class="upload-img-form" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="mb-5">Upload Image</legend>
          <div class="form-group">
            {{ form.file.label() }}
            {{ form.file(class="form-control-file") }}
            {% if form.file.errors %}
              {% for error in form.file.errors %}
                <span class="danger">{{ error }}</span><br>
              {% endfor %}
            {% endif %}
          </div>
        </fieldset>
        <div class="form-group" id="uploadImageButton">
          {{ form.submit(class="btn btn-primary") }}
        </div>
      </form>
    </div>
  </div>
{% endblock content %}